### ISSUE TITLE
Add php*-sybase deb package

### ISSUE THREAD

**Issue by pquerner** [JeroenBoersma/docker-php#5]
php*-sybase [1] contains the module to work with MsSQL databases. Would be neat to have this added right out of the box.

-- Or

Could you tell us how to add this package to https://github.com/JeroenBoersma/docker-compose-development ?

Links:
https://packages.debian.org/de/sid/php/php-sybase
https://packages.debian.org/de/sid/php/php5-sybase
https://packages.debian.org/de/sid/php/php7.0-sybase
https://packages.debian.org/de/sid/php/php7.1-sybase
https://packages.debian.org/de/sid/php/php7.2-sybase

**Comment by JeroenBoersma** [comment]
I'll explain in docker-compose-development branch
